POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "shilongswarme@gmail.com",
    "password": "amanshukla123@"
}
###  //plan_PQeaAFl0gR0cj8
POST http://localhost:3000/api/payment/createPlan 
Content-Type: application/json

{
  "name":"GOLD",
  "amount":"1000",
  "currency":"INR",
  "interval":"month"
}

###
POST http://localhost:3000/api/payment/createSubscription
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFmY2NiZWYxNTJmNGY1MzQxMjgwYzYiLCJpYXQiOjE3MDYwMjg3OTIsImV4cCI6MTcwNjA2NDc5Mn0.JItOYGR7eRCn_bJ3Tn-5JF-7kzU7u8mp_4JDUWO9IQQ
Content-Type: application/json

{
    "planId": "plan_PQfnHJ2Xc0WJ3y",
    "business_id":"65afbe87b50118fde7d910c7"
}